### ISSUE TITLE
Support English

### ISSUE THREAD

**Issue by BG8LGP** [Jehxon/MorseTrainer#1]
I'm interesting in this app, but I can't read the language of this app.

**Comment by Jehxon** [comment]
I didn't think anyone besides my french friends would be interested. I just added english support. The language of the app is now based on the language of your phone. It supports only french and english, and the default is english.
Let me know if I forgot any translations ! I will close the issue for now.

**Comment by BG8LGP** [comment]
I am a Chinese user and the default language of this application is French. I tried to switch the system language to English, but when I opened the application, it still displayed French. I don't know where the problem was.

**Comment by BG8LGP** [comment]
I noticed that you have released a new version and added English language, which has been very helpful to me. Thank you.
I am a Chinese user, and if possible, I can also help you translate the application into Chinese. Please tell me what to do, I am not a professional developer.

**Comment by Jehxon** [comment]
You're welcome.
Sure ! Translating it in Chinese sounds fun, thank you. To do that you will find all the text of the app in the file "lib/l10n/app_en.arb" in the project. You can translate it (only the right side of each fields) and send it to me, I will integrate it. I am unsure if Chinese characters will be supported easily though... We'll see !
