### ISSUE TITLE
Chinese (Simplified) Support

### ISSUE THREAD

**Issue by BG8LGP** [Jehxon/MorseTrainer#2]
I did not use a direct translation from English to Chinese, but used the localized translation method。

file name: app_zh.arb

```
{
    "dictPath": "assets/data/english_dict_freq.txt",

    "cancel": "取消",
    "confirm": "确认",
    "giveUp": "放弃",
    "listenButton": "听",
    "nbSuccessiveGoodGuesses": "当前得分",
    "highscore": "最高得分",

    "guessLetterTitle": "听抄字母",

    "guessSoundTitle": "发送练习",
    "pressButton": "按此处!",

    "guessWordTitle": "听抄单词",

    "categoryParameter": "模式",
    "generalParameters": "通用",
    "themeParameter": "更改主题",
    "playBackSpeedParameter": "播放速度",
    "soundFrequencyParameter": "音调 (Hz)",
    "includeNumbersAndSpecialCharactersParameter": "包含数字和符号",

    "numberOfGuesses": "选项数量",
    "showLetterSound": "显示电码",

    "nbWordsParameter": "词典单词数",
    "nbWordsParameterSubtitle1": "在词典中选择频率最高的",
    "nbWordsParameterSubtitle2": "个词组",
    "tempoBetweenLetters": "两个字母之间的间隔",
    "tempoBetweenLettersSubtitle": "一个间隔时间是一个 '\u2022' 的时长. 一个 '-' 的时长是3个间隔. 如果您不知道字母何时结束, 请增加该值. 默认值是3.",

    "pickColor": "选择一个颜色",

    "parameters": "参数设置",
    "previousPage": "返回"
}
```
Here's an additional suggestion:  
It's fine to use an English dictionary, but maybe we can add an option to import a user's custom dictionary. what do you think?

**Comment by Jehxon** [comment]
Thanks ! I added it to the app. I noticed that I forgot the word "Alphabet" in the main menu, so I added it in. I used google translate and it gave me " 字母表 ". I do not know Chinese at all, is it an appropriate translation in this case ?

For your suggestion, I think it is a good idea. I encourage you to make the modifications yourself ! You can fork the project and create a pull request.
You will need to have flutter installed on your computer, and if you can keep the 'apk' folder updated with the latest build once everything works fine, that would be great.

**Comment by BG8LGP** [comment]
The " 字母表 " is good for me.
